Feat/non blocking for loading game info
MegaGlest/megaglest-source pull request #240
Opened 2022-08-07 18:28 UTC by pavanvo

This PR solving issue with main thread blocking, on loading .xml file with saved game.
Also this code can be used somewhere else
fixes #233

2022-08-08 11:49 UTC, Rampoina commented on source/glest_game/menu/menu_state_load_game.cpp
> +                        infoTextLabel.setText("Loading...");
Spaces vs tabs, this codebase uses mostly tabs, let's try to keep it consistent :)

2022-08-08 11:49 UTC, Rampoina commented on source/shared_lib/include/xml/xml_parser.h
> +#include "callback.h"
you forgot to include memory

2022-08-08 11:52 UTC, Rampoina requested changes
Tested, works fine on my system  :+1:

2022-08-08 11:54 UTC, Rampoina requested changes

2022-08-08 11:54 UTC, Rampoina commented on source/shared_lib/include/util/callback.h
> +#pragma once
This is done in other places of the code with https://github.com/MegaGlest/megaglest-source/blob/develop/source/shared_lib/include/platform/common/simple_threads.h#L71
Although honestly your way seems cleaner to me.

2022-08-13 21:44 UTC, andy5995 reviewed
I see this is passing the Linux CI, but the build fails for me on Manjaro, using g++ (GCC) 12.1.1 20220730

```
[ 45%] Building CXX object source/shared_lib/CMakeFiles/libmegaglest.dir/sources/lua/lua_script.cpp.o
In file included from /home/andy/src/megaglest-source/source/shared_lib/include/util/utf8.h:31,
                 from /home/andy/src/megaglest-source/source/shared_lib/sources/graphics/gl/text_renderer_gl.cpp:21:
/home/andy/src/megaglest-source/source/shared_lib/include/util/utf8/checked.h:268:34: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
  268 |     class iterator : public std::iterator <std::bidirectional_iterator_tag, uint32_t> {
      |                                  ^~~~~~~~
In file included from /usr/include/c++/12.1.1/string:45,
                 from /home/andy/src/megaglest-source/source/shared_lib/include/graphics/text_renderer.h:15,
                 from /home/andy/src/megaglest-source/source/shared_lib/include/graphics/gl/text_renderer_gl.h:15,
                 from /home/andy/src/megaglest-source/source/shared_lib/sources/graphics/gl/text_renderer_gl.cpp:12:
/usr/include/c++/12.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
In file included from /home/andy/src/megaglest-source/source/shared_lib/include/util/utf8.h:32:
/home/andy/src/megaglest-source/source/shared_lib/include/util/utf8/unchecked.h:179:40: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
  179 |           class iterator : public std::iterator <std::bidirectional_iterator_tag, uint32_t> {
      |                                        ^~~~~~~~
/usr/include/c++/12.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[ 45%] Building CXX object source/shared_lib/CMakeFiles/libmegaglest.dir/sources/map/map_preview.cpp.o
In file included from /home/andy/src/megaglest-source/source/shared_lib/include/lua/lua_script.h:18,
                 from /home/andy/src/megaglest-source/source/shared_lib/sources/lua/lua_script.cpp:12:
/home/andy/src/megaglest-source/source/shared_lib/include/xml/xml_parser.h:156:10: error: 'shared_ptr' in namespace 'std' does not name a template type
  156 |     std::shared_ptr<CallBack<void>> loadAsync(const string &path, const std::map<string,string> &mapTagReplacementValues, bool noValidation=false,bool skipStackCheck=false,bool skipStackTrace=false);
      |          ^~~~~~~~~~
/home/andy/src/megaglest-source/source/shared_lib/include/xml/xml_parser.h:27:1: note: 'std::shared_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   26 | #include "callback.h"
  +++ |+#include <memory>
   27 | #include "data_types.h"
[ 46%] Building CXX object source/shared_lib/CMakeFiles/libmegaglest.dir/sources/platform/common/base_thread.cpp.o
make[2]: *** [source/shared_lib/CMakeFiles/libmegaglest.dir/build.make:706: source/shared_lib/CMakeFiles/libmegaglest.dir/sources/lua/lua_script.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/andy/src/megaglest-source/source/shared_lib/sources/platform/common/base_thread.cpp: In destructor 'virtual Shared::PlatformCommon::BaseThread::~BaseThread()':
/home/andy/src/megaglest-source/source/shared_lib/sources/platform/common/base_thread.cpp:95:17: warning: 'throw' will always call 'terminate' [-Wterminate]
   95 |                 throw megaglest_runtime_error(szBuf);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/andy/src/megaglest-source/source/shared_lib/sources/platform/common/base_thread.cpp:95:17: note: in C++11 destructors default to 'noexcept'
make[1]: *** [CMakeFiles/Makefile2:227: source/shared_lib/CMakeFiles/libmegaglest.dir/all] Error 2
make: *** [Makefile:111: all] Error 2
ERROR: MAKE failed.
```

@Jammyjamjamman are you able to build this?

2022-08-14 00:16 UTC, Rampoina commented
@andy5995 like I mentioned in the other comment, @pavanvo forgot to #include <memory> like the compiler tells you

2025-02-02 23:32 UTC, andy5995 commented
This was last worked on three years ago and hasn't been declined, so I'll merge it now and if any problems come up during dev testing we can easily revert it.

2025-02-02 23:32 UTC, merged

2025-02-02 23:38 UTC, andy5995 commented
@pavanvo This is merged, but failing on macos. Would you be willing to fix the macos build soon? Otherwise I will have to unmerge this.

https://github.com/MegaGlest/megaglest-source/actions/runs/13103512668/job/36554707510

2025-02-03 02:18 UTC, andy5995 commented
> @pavanvo This is merged, but failing on macos. Would you be willing to fix the macos build soon? Otherwise I will have to unmerge this.
> 
> https://github.com/MegaGlest/megaglest-source/actions/runs/13103512668/job/36554707510

@pavanvo I think https://github.com/MegaGlest/megaglest-source/pull/300 will fix this.